name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TAJIK_AIR_KEY_ALIAS: ${{ secrets.TAJIK_AIR_KEY_ALIAS }}
      TAJIK_AIR_KEY_PASSWORD: ${{ secrets.TAJIK_AIR_KEY_PASSWORD }}
      TAJIK_AIR_KEYSTORE_PASSWORD: ${{ secrets.TAJIK_AIR_KEYSTORE_PASSWORD }}
      TAJIK_AIR_KEYSTORE_PATH: ${{ secrets.TAJIK_AIR_KEYSTORE_PATH }}

    steps:
      ## Checkout repository ###
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      ## Build all Build Types at once ##
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

      ## Sign artifact##
      - name: Sign artifact
        # ID used to access action output
        id: sign_app
        uses: r0adkll/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.TAJIK_AIR_KEY_ALIAS }}
          signingKeyBase64: ${{ secrets.TAJIK_AIR_KEYSTORE }}
          keyStorePassword: ${{ secrets.TAJIK_AIR_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.TAJIK_AIR_KEY_PASSWORD }}

      - name: Check signed path
        run: echo "Signed apk output = ${{steps.sign_app.outputs.signedReleaseFile}}"

      - name: Upload APK
        id: upload_apk
        uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

